package localsearch;

public enum EnumLocalSearchStep {
    //ADD
    ADD_SINGLE_PRODUCTION,
    ADD_SHIPPING_DAY,
    ADD_PRODUCTION_AFTER_PLANNED_PRODUCTION,

    //CHANGE
    CHANGE_PRODUCTION,

    //MOVE
    MOVE_MAINTENANCE,
    MOVE_PRODUCTION,
    MOVE_SHIPPING_DAY,

    //OTHER
    JOIN_SINGLE_NEIGHBOURING_SETUPS,

    //REMOVE
    REMOVE_PRODUCTION,
}
