package localsearch;

public enum EnumStep {
    ADD_SINGLE_PRODUCTION, MOVE_MAINTENANCE,
    ADD_PRODUCTION_FOR_SHIPPING, CHANGE_PRODUCTION,
    REMOVE_PRODUCTION, MOVE_PRODUCTION,
    MOVE_SHIPPING_DAY, PLAN_SHIPPING_DAY,
    JOIN_NEIGHBOURING_SETUPS
}
